<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <RootNamespace>dddlib.Persistence.Projections.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/dddlib/dddlib.csproj" />
    <ProjectReference Include="../../src/dddlib.Generators/dddlib.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/dddlib.Persistence/dddlib.Persistence.csproj" />
    <ProjectReference Include="../../src/dddlib.Persistence.Projections/dddlib.Persistence.Projections.csproj" />
    <ProjectReference Include="../../src/dddlib.Persistence.Projections.SqlServer/dddlib.Persistence.Projections.SqlServer.csproj" />
    <ProjectReference Include="../../src/dddlib.Persistence.SqlServer/dddlib.Persistence.SqlServer.csproj" />
    <ProjectReference Include="../../src/dddlib.Persistence.EventDispatcher.SqlServer/dddlib.Persistence.EventDispatcher.SqlServer.csproj" />
    <ProjectReference Include="../../src/dddlib.TestFramework/dddlib.TestFramework.csproj" />
    <ProjectReference Include="../dddlib.Tests.Support/dddlib.Tests.Support.csproj" />
  </ItemGroup>

</Project>
