using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace dddlib.Generators;

internal sealed record BootstrapperRegistration(string FullyQualifiedName, bool IsAccessible, bool HasPublicParameterlessConstructor);

/// <summary>
/// Registers the assembly's single <c>IBootstrapper</c> with the runtime at module initialization, so that the
/// runtime does not scan the assembly. Emits nothing when the assembly is not in a state the runtime would accept;
/// the analyzer reports why.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BootstrapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var bootstrappers = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (syntaxContext, cancellationToken) => Transform(syntaxContext, cancellationToken))
            .Where(static model => model is not null)
            .Collect();

        var referencesDddlib = context.CompilationProvider.Select(static (compilation, _) => KnownSymbols.Create(compilation) is not null);

        context.RegisterSourceOutput(bootstrappers.Combine(referencesDddlib), static (productionContext, pair) => Emit(productionContext, pair.Left!, pair.Right));
    }

    private static BootstrapperRegistration? Transform(GeneratorSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node, cancellationToken) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.DeclaringSyntaxReferences[0].GetSyntax(cancellationToken) != context.Node)
        {
            return null;
        }

        var known = KnownSymbols.Create(context.SemanticModel.Compilation);
        if (known is null || !known.IsBootstrapper(symbol))
        {
            return null;
        }

        var isAccessible = !symbol.IsGenericType && context.SemanticModel.Compilation.IsSymbolAccessibleWithin(symbol, context.SemanticModel.Compilation.Assembly);

        return new BootstrapperRegistration(symbol.ToDisplayString(SymbolExtensions.FullyQualified), isAccessible, symbol.HasPublicParameterlessConstructor());
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<BootstrapperRegistration?> bootstrappers, bool referencesDddlib)
    {
        if (!referencesDddlib)
        {
            return;
        }

        string registration;
        if (bootstrappers.Length == 0)
        {
            registration = "global::dddlib.Sdk.Generated.BootstrapperRegistry.RegisterNone(typeof(__DddlibBootstrapperRegistration).Assembly);";
        }
        else if (bootstrappers.Length == 1 && bootstrappers[0] is { IsAccessible: true, HasPublicParameterlessConstructor: true } bootstrapper)
        {
            registration = $"global::dddlib.Sdk.Generated.BootstrapperRegistry.Register(typeof({bootstrapper.FullyQualifiedName}));";
        }
        else
        {
            return;
        }

        context.AddSource("dddlib.BootstrapperRegistration.g.cs", $$"""
            // <auto-generated/>
            #pragma warning disable

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("dddlib.Generators", "2.0.0")]
            internal static class __DddlibBootstrapperRegistration
            {
                [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
                internal static void Register() => {{registration}}
            }

            """);
    }
}
