using System.Text;

namespace dddlib.Generators;

internal static class SourceEmitter
{
    private const string Version = "2.0.0";

    public static string Emit(DomainTypeModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine();

        var indent = 0;
        if (model.Namespace is not null)
        {
            builder.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();
        }

        foreach (var container in model.Containers)
        {
            Line(builder, indent, $"partial {container.Keyword} {container.Name}");
            Line(builder, indent, "{");
            indent++;
        }

        Line(builder, indent, $"partial {model.Keyword} {model.Name}");
        Line(builder, indent, "{");
        indent++;

        switch (model.Kind)
        {
            case DomainTypeKind.AggregateRoot:
                EmitAggregateRoot(builder, model, indent);
                break;
            case DomainTypeKind.Entity:
                EmitEntity(builder, model, indent);
                break;
            case DomainTypeKind.ValueObject:
                EmitValueObject(builder, model, indent);
                break;
        }

        while (indent > 0)
        {
            indent--;
            Line(builder, indent, "}");
        }

        return builder.ToString();
    }

    private static void EmitAggregateRoot(StringBuilder builder, DomainTypeModel model, int indent)
    {
        EmitMetadataHeader(builder, indent, "global::dddlib.Sdk.Generated.IGeneratedAggregateRootMetadata");
        EmitNaturalKeyMembers(builder, model, indent + 1);

        builder.AppendLine();
        Line(builder, indent + 1, model.HasUninitializedFactory
            ? $"public global::System.Delegate? UninitializedFactory => (global::System.Func<{model.FullyQualifiedName}>)(static () => new {model.FullyQualifiedName}());"
            : "public global::System.Delegate? UninitializedFactory => null;");

        builder.AppendLine();
        Line(builder, indent + 1, "public void Dispatch(object target, object @event)");
        Line(builder, indent + 1, "{");
        if (model.HandlerEventTypes.Count > 0)
        {
            Line(builder, indent + 2, $"var self = ({model.FullyQualifiedName})target;");
            Line(builder, indent + 2, "var eventType = @event.GetType();");
            foreach (var eventType in model.HandlerEventTypes)
            {
                Line(builder, indent + 2, $"if (eventType == typeof({eventType}))");
                Line(builder, indent + 2, "{");
                Line(builder, indent + 3, $"self.Handle(({eventType})@event);");
                Line(builder, indent + 3, "return;");
                Line(builder, indent + 2, "}");
            }
        }

        Line(builder, indent + 1, "}");
        Line(builder, indent, "}");
    }

    private static void EmitEntity(StringBuilder builder, DomainTypeModel model, int indent)
    {
        EmitMetadataHeader(builder, indent, "global::dddlib.Sdk.Generated.IGeneratedEntityMetadata");
        EmitNaturalKeyMembers(builder, model, indent + 1);
        Line(builder, indent, "}");
    }

    private static void EmitValueObject(StringBuilder builder, DomainTypeModel model, int indent)
    {
        var argument = model.ValueObjectArgument!;
        EmitMetadataHeader(builder, indent, $"global::dddlib.Sdk.Generated.IGeneratedValueObjectMetadata, global::System.Collections.Generic.IEqualityComparer<{argument}>");
        Line(builder, indent + 1, "public object EqualityComparer => this;");

        builder.AppendLine();
        Line(builder, indent + 1, $"public bool Equals({argument}? x, {argument}? y)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "if (x is null || y is null)");
        Line(builder, indent + 2, "{");
        Line(builder, indent + 3, "return x is null && y is null;");
        Line(builder, indent + 2, "}");
        builder.AppendLine();
        Line(builder, indent + 2, "return ReferenceEquals(x, y)");
        for (var index = 0; index < model.ValueObjectProperties.Count; index++)
        {
            var property = model.ValueObjectProperties[index];
            var prefix = index == 0 ? "|| (" : "&& ";
            var suffix = index == model.ValueObjectProperties.Count - 1 ? ");" : string.Empty;
            Line(builder, index == 0 ? indent + 3 : indent + 4, $"{prefix}global::dddlib.Sdk.ValueObjectEquality.ValuesEqual(x.{property}, y.{property}){suffix}");
        }

        Line(builder, indent + 1, "}");

        builder.AppendLine();
        Line(builder, indent + 1, $"public int GetHashCode({argument} obj)");
        Line(builder, indent + 1, "{");
        Line(builder, indent + 2, "var hash = global::dddlib.Sdk.ValueObjectEquality.HashSeed;");
        foreach (var property in model.ValueObjectProperties)
        {
            Line(builder, indent + 2, $"hash = global::dddlib.Sdk.ValueObjectEquality.CombineHash(hash, obj.{property});");
        }

        Line(builder, indent + 2, "return hash;");
        Line(builder, indent + 1, "}");
        Line(builder, indent, "}");
    }

    private static void EmitMetadataHeader(StringBuilder builder, int indent, string interfaces)
    {
        Line(builder, indent, $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"dddlib.Generators\", \"{Version}\")]");
        Line(builder, indent, "[global::System.Diagnostics.DebuggerNonUserCodeAttribute]");
        Line(builder, indent, $"private sealed class __DddlibMetadata : {interfaces}");
        Line(builder, indent, "{");
    }

    private static void EmitNaturalKeyMembers(StringBuilder builder, DomainTypeModel model, int indent)
    {
        if (model.NaturalKeyPropertyName is null)
        {
            Line(builder, indent, "public string? NaturalKeyPropertyName => null;");
            builder.AppendLine();
            Line(builder, indent, "public global::System.Type? NaturalKeyPropertyType => null;");
            builder.AppendLine();
            Line(builder, indent, "public object? GetNaturalKeyValue(global::dddlib.Entity entity) => null;");
            return;
        }

        Line(builder, indent, $"public string? NaturalKeyPropertyName => \"{model.NaturalKeyPropertyName}\";");
        builder.AppendLine();
        Line(builder, indent, $"public global::System.Type? NaturalKeyPropertyType => typeof({model.NaturalKeyPropertyType});");
        builder.AppendLine();
        Line(builder, indent, $"public object? GetNaturalKeyValue(global::dddlib.Entity entity) => (({model.FullyQualifiedName})entity).{model.NaturalKeyPropertyName};");
    }

    private static void Line(StringBuilder builder, int indent, string text) => builder.Append(' ', indent * 4).AppendLine(text);
}
