<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <PropertyGroup>
    <TUnitVersion>1.71.0</TUnitVersion>
  </PropertyGroup>

  <ItemGroup Label="App Dependencies">
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.1.0" />
  </ItemGroup>

  <ItemGroup Label="Generator Dependencies">
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" />
    <PackageVersion Include="PolySharp" Version="1.16.0" />
  </ItemGroup>

  <ItemGroup Label="Test Dependencies">
    <PackageVersion Include="Testcontainers.MsSql" Version="4.15.0" />
    <PackageVersion Include="PublicApiGenerator" Version="11.5.4" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="TUnit" Version="$(TUnitVersion)" />
    <PackageVersion Include="TUnit.Core" Version="$(TUnitVersion)" />
    <PackageVersion Include="TUnit.Assertions" Version="$(TUnitVersion)" />
  </ItemGroup>

</Project>
