<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetLibVersion)</TargetFramework>
    <RootNamespace>dddlib</RootNamespace>
    <Description>A domain driven design library for .NET.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="dddlib.Persistence" />
    <InternalsVisibleTo Include="dddlib.Tests" />
    <InternalsVisibleTo Include="dddlib.Persistence.Tests" />
    <InternalsVisibleTo Include="dddlib.Tests.Support" />
  </ItemGroup>

</Project>
