<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetLibVersion)</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>dddlib.Benchmarks</RootNamespace>
    <IsPackable>false</IsPackable>
    <!-- BenchmarkDotNet wants public benchmark classes with public parameterless constructors. -->
    <NoWarn>$(NoWarn);CA1822;CA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/dddlib/dddlib.csproj" />
    <ProjectReference Include="../../src/dddlib.Generators/dddlib.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
