<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <RootNamespace>dddlib.Tests.Support</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Testcontainers.MsSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/dddlib/dddlib.csproj" />
    <ProjectReference Include="../../src/dddlib.Generators/dddlib.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../src/dddlib.Persistence/dddlib.Persistence.csproj" />
  </ItemGroup>

</Project>
