<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <RootNamespace>dddlib.Generators.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/dddlib/dddlib.csproj" />
    <ProjectReference Include="../../src/dddlib.Generators/dddlib.Generators.csproj" />
  </ItemGroup>

</Project>
